<?php
/**
 * @file
 * Contains d8t_system.module..
 */
use Drupal\d8t_system\Controller\ParagraphViewController;
use Drupal\d8t_system\Controller\BlockViewController;

/**
* Implements hook_preprocess_block().
*/
function d8t_system_preprocess_block(&$variables){
  $blockView = new BlockViewController();
  return $blockView->render($variables);
}

/**
* Implements hook_preprocess_paragraph().
*/
function d8t_system_preprocess_paragraph(&$variables) {
  $paragraphView = new ParagraphViewController();
  return $paragraphView->render($variables);
}
